version: '3'
services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: php:8.3
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - ${NGINX_PORT_IN_80}:${NGINX_PORT_OUT_80}
    networks:
      - app-network

  # MySQL Service
  mysql:
    image: 'mysql:8.0'
    container_name: ${CONTAINER_MYSQL_NAME}
    restart: unless-stopped
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: mastersUser
      MYSQL_TCP_PORT: ${MYSQL_PORT_OUT}
    ports:
      - ${MYSQL_PORT_IN}:${MYSQL_PORT_OUT}
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
